"""Session-local diarization benchmark domain models."""

from keyframe.diarization.attribution import apply_session_local_attribution
from keyframe.diarization.bundles import (
    CandidateBundle,
    CandidateBundleMode,
    ReferenceBundle,
    build_candidate_bundle,
    build_candidate_bundle_from_recording,
    validate_candidate_bundle_payload,
)
from keyframe.diarization.io import (
    canonical_json_dumps,
    canonical_json_loads,
    canonical_jsonl_dumps,
    canonical_jsonl_loads,
    read_recording_json,
    read_recordings_jsonl,
    recording_from_dict,
    recording_to_dict,
    validate_schema_version,
    write_recording_json,
    write_recordings_jsonl,
)
from keyframe.diarization.models import (
    CanonicalRecording,
    CanonicalWord,
    ChannelRecord,
    DisplayLabel,
    ScoringRegion,
    SpeakerRecord,
    SpeakerSpan,
    TimeBasis,
    ValidationError,
)
from keyframe.diarization.provenance import (
    ArtifactKind,
    AudioTimelineProvenance,
    NormalizedArtifactProvenance,
    OffsetMapSegment,
    TimelineMergeValidation,
    TimelineOffsetMap,
    TransformChain,
    TransformStep,
    TransformType,
    boundary_shift_degrades_scoring,
    validate_timeline_merge,
)

__all__ = [
    "CanonicalRecording",
    "CanonicalWord",
    "ChannelRecord",
    "DisplayLabel",
    "ScoringRegion",
    "SpeakerRecord",
    "SpeakerSpan",
    "TimeBasis",
    "ValidationError",
    "ArtifactKind",
    "AudioTimelineProvenance",
    "CandidateBundle",
    "CandidateBundleMode",
    "NormalizedArtifactProvenance",
    "OffsetMapSegment",
    "ReferenceBundle",
    "TimelineMergeValidation",
    "TimelineOffsetMap",
    "TransformChain",
    "TransformStep",
    "TransformType",
    "apply_session_local_attribution",
    "boundary_shift_degrades_scoring",
    "build_candidate_bundle",
    "build_candidate_bundle_from_recording",
    "canonical_json_dumps",
    "canonical_json_loads",
    "canonical_jsonl_dumps",
    "canonical_jsonl_loads",
    "read_recording_json",
    "read_recordings_jsonl",
    "recording_from_dict",
    "recording_to_dict",
    "validate_schema_version",
    "validate_candidate_bundle_payload",
    "validate_timeline_merge",
    "write_recording_json",
    "write_recordings_jsonl",
]
